# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pb_pb2 as pb__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MangaStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Channel1 = channel.unary_unary(
                '/manga.Manga/Channel1',
                request_serializer=pb__pb2.CallbackRequest.SerializeToString,
                response_deserializer=pb__pb2.CallbackReply.FromString,
                _registered_method=True)


class MangaServicer(object):
    """The greeting service definition.
    """

    def Channel1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MangaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Channel1': grpc.unary_unary_rpc_method_handler(
                    servicer.Channel1,
                    request_deserializer=pb__pb2.CallbackRequest.FromString,
                    response_serializer=pb__pb2.CallbackReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manga.Manga', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('manga.Manga', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Manga(object):
    """The greeting service definition.
    """

    @staticmethod
    def Channel1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manga.Manga/Channel1',
            pb__pb2.CallbackRequest.SerializeToString,
            pb__pb2.CallbackReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NovelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Channel1 = channel.unary_unary(
                '/manga.Novel/Channel1',
                request_serializer=pb__pb2.CallbackRequest.SerializeToString,
                response_deserializer=pb__pb2.CallbackReply.FromString,
                _registered_method=True)


class NovelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Channel1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NovelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Channel1': grpc.unary_unary_rpc_method_handler(
                    servicer.Channel1,
                    request_deserializer=pb__pb2.CallbackRequest.FromString,
                    response_serializer=pb__pb2.CallbackReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manga.Novel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('manga.Novel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Novel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Channel1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manga.Novel/Channel1',
            pb__pb2.CallbackRequest.SerializeToString,
            pb__pb2.CallbackReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
